---
output:
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/Professional/portfolio/svm-r-markdown-templates/svm-latex-resume.tex
geometry: margin=1in
  
title: "CV"
author: "Nathan Mietkiewicz, Ph. D."
email: Mietkiewicz@battelleecology.org

jobtitle: Environmental Data Scientist
fontawesome: yes
phone: 508 797 2940
address: 'National Ecological Observation Network/ Battelle · Boulder · CO '
web: 'nathanmietkiewicz.com'
github: 'NateMietk'
location: 'Boulder, CO'
twitter: "@natemietk"
linkedin: "nathan-mietkiewicz-54506a158"


fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: blue
urlcolor: blue
---
# Professional Summary
I am a geospatial scientist and ecologist seeking a research position in a dynamic and broad-thinking lab that allows me to pursue high-caliber science relevant to pressing human-environmental issues. My current research examines how global environmental change, including changed climate and fire cycles, alters ecosystem function and human vulnerability. Specifically, I lead cutting-edge research in wildfire ecology, with particular focus on quantifying, modeling, and predicting the consequences of human-started wildfires to the vulnerability of communities throughout the United States. I work at multiple scales, across disciplines, and with an international community of scientists. 

# Language Competencies and Technical Skills

**Programming**: R (expert), Python (general understanding), R Markdown, Docker, GitHub, UNIX Shell Programming

**Applications**: RStudio, Jupyter Notebooks, Amazon Web Services (S3, EC2), ArcGIS Platform, QGis, IDRISI/Terrset, Adobe CS6 Illustrator

# Recent Professional Background
**Environmental Data Scientist** \hfill Oct 2019 -- Present

*National Ecological Observation Network, Battelle, Boulder, CO*

- -Developed reproducible, automated workflows to generate monthly metric reports using both internal (i.e., HA Proxy logs) and external API (i.e., Google Analytics, auth0, Lime Survey) data tracking services.
- -Developed R code to determine data availability for for over 200 data products across 81 different sites in the observatory.
- -Wrote enhancements to the [neonUtilities R package](https://github.com/NEONScience/NEON-utilities)
- -Built a number of Shiny Applications for internal use 
- -A member of multiple internal working groups, such as Public Code Working Group, Science Code Working Group, and the Power Bi Working Group
- -Co-chaired on the Data Standards Technical External Working Group

**Postdoctoral Research Associate** \hfill Aug 2016-- Sept 2019

*Earth Lab and the Cooperative Institute for Research in Environmental Sciences, University of Colorado at Boulder*

- -Deployed geospatial, reproducible workflows in a salable, cloud-compute environment via Amazon Web Services (AWS) leveraging Docker and GitHub to build stable, collaborative work environments across platforms.
- -Wrote clean, efficient, reproducible R code to analyze big geospatial data.
- -Built out and optimizing statistical models using a variety of techniques, with focus on machine learning algorithms.
- -Mentored/managed undergraduate and graduate level interns and research assistants.
- -Authored and co-authored 6 peer-review publications with 3 more in review and 10 in progress.
- -Authored and Co-authored over $15 million in research grant proposals.

**Research Assistant** \hfill 2013-2016

*Graduate School of Geography, Clark University, Worcester, MA*

- -Developed and led a successful field campaign located in the backcountry of the Colorado Rockies
- -Managed a team of 8 undergraduate and graduate students in remote, mountainous areas for 18 weeks over the course of 2 summers
- -Collected over 2,000 tree cores, 1,000 seedling/sampling samples, and data ranging over 3 projects, resulting in 4 peer-reviewed publications and my dissertation
- -Synthesized field data that was fed into large wildfire behavior prediction models under current and 3 future climate scenarios across the Southern Rocky Mountains.
- -Managed the Forest Ecology Lab, where duties included maintaining, ordering, inventorying, and supporting both computer and field equipment for the research and classroom laboratories

**Adjunct Faculty** \hfill 2012-2016

*Graduate School of Geography, Clark University, Worcester, MA*

- -Taught the undergraduate Forest Ecology seminar
- -Developed all course materials, syllabi, laboratories, and testing materials
- -Overall effectiveness based on student evaluations was 92%

**Teaching Assistant** \hfill 2012-2016

*Graduate School of Geography, Clark University, Worcester, MA*

- -Taught technical laboratories for graduate and undergraduate class, including Advanced Topics in GIS: Raster GIS (3 semesters), Introduction to Remote Sensing (1 semester), Forest Ecology (1 semester), and Earth System Science (1 semester)
- -Overall effectiveness based on student evaluations ranging from 92%-99%, with an average evaluation of 96% over 6 semesters

# Academic Background
*Clark University, Worcester, MA*, **Ph.D**. Geography \hfill 2016 \
*Clark University, Worcester, MA*, **M.A.**, Geography, \hfill 2015 \
*Clark University, Worcester, MA*, **M.S.**, GIS for Development and Environment, \hfill 2013 \
*University of Maine, Orono, ME*, **B.S.**, Earth Science, \hfill 2009

# Selected Peer-reviewed Publications 

**Mietkiewicz, N.**, J. K. Balch, T. Schoennagel, S. Leyk, L. St. Denis, B. Bradley. (Accepted) *In the line of fire: Consequences of human-ignited wildfires to homes in the U.S. (1992-2015)*. Fire.

Leyk, S., Uhl, J.H., Connor, D.S., Braswell, A.E., **Mietkiewicz, N.**, Balch, J.K., Gutmann, M. (2020). *Two centuries of settlement and urban development in the United States.* Science Advances. 6(23), doi:10.1126/sciadv.aba2937.

**Mietkiewicz, N.**, D. Kulakowski, and T. T. Veblen 2018. *Pre‐outbreak forest conditions mediate the effects of spruce beetle outbreaks on fuels in subalpine forests of Colorado*. Ecological Applications 28:457-472.

**Mietkiewicz, N.**, D. Kulakowski, D. Rogan, and P. Bebi. 2017. *Long-term change in sub-alpine forest cover, tree line and species composition in the Swiss Alps*. Journal of Vegetation Science. 28:951-964. DOI: 10.1111/jvs.12561.

Schoennagel, T., J. K. Balch, H. Brenkert-Smith, P. E. Dennison, B. J. Harvey, M. A. Krawchuk, **N. Mietkiewicz**, P. Morgan, M. A. Moritz, R. Rasker, M. G. Turner, and C. Whitlock. 2017. *Adapt to more wildfire in western North American forests as climate changes*. Proceedings of the National Academy of Sciences. 114:4582-4590.

**Mietkiewicz, N.** and D. Kulakowski. 2016. *Relative importance of climate and mountain pine beetle outbreaks on the occurrence of large wildfires in the western US*. Ecological Applications:10.1002/eap.1400.